GET  http://localhost:3333/api/beers/
Content-Type: application/json

##################

get http://localhost:3333/api/beers/5
Content-Type: application/json

##################

POST http://localhost:3333/api/beers/
Content-Type: application/json

 {
    "name": "Kalian",
    "type": "Black IPA",
    "houblon": [
      {
        "name": "Nelson",
        "origin": "US",
        "quantity": 580
      }
    ],
    "malts": [
      {
        "name": "chocolat",
        "origin": "US",
        "quantity": 1200
      }
    ],
    "levure": "MS-U44",
    "price": 53,
    "etiquette": "https://static.pratique.fr/images/unsized/et/etiquette-champagne.jpg"
  }

###################


PUT http://localhost:3333/api/beers/5
Content-Type: application/json

{
    "name": "Wild JS",
    "type": "Ambré",
    "houblon": [
      {
        "name": "citra",
        "origin": "US",
        "quantity": 580
      }
    ],
    "malts": [
      {
        "name": "flocon de froment",
        "origin": "US",
        "quantity": 580
      }
    ],
    "levure": "MS-U44",
    "price": 63,
    "etiquette": "https://static.pratique.fr/images/unsized/et/etiquette-champagne.jpg"
  }

####################

DELETE http://localhost:3333/api/beers/5