GET  http://localhost:3333/api/users/
Content-Type: application/json

##################

GET http://localhost:3333/api/users/13
Content-Type: application/json


##################

GET http://localhost:3333/api/users/nelson.ntepp@icloud.com
Content-Type: application/json


##################

GET http://localhost:3333/api/users/Neruso1
Content-Type: application/json


##################

POST http://localhost:3333/api/auth/signup
Content-Type: application/json

 {
    "username": "Kalian",
    "password": "Azerty123*",
    "email": "kalian.iglesias@gmail.com"
  }

##################

POST http://localhost:3333/api/auth/signin
Content-Type: application/json

 {
    "username": "Kalian",
    "password": "yyr5wzfph3emV*"
  }

###################


PUT http://localhost:3333/api/auth/update/13
Content-Type: application/json

{
    "username": "Kalian",
    "email": "kalian.iglesias@gmail.com",
    "password": "yyr5wzfph3emV*"
}

####################

DELETE http://localhost:3333/api/users/14