GET  http://localhost:3333/users/1
Content-Type: application/json

##################

get http://localhost:3333/api/users/email
Content-Type: application/json

{
  "email": "nelson.ntepp@icloud.com"
}

##################

POST http://localhost:3333/auth/signup
Content-Type: application/json

 {
    "username": "nuxdz",
    "password": "Azertyzofn",
    "email": "exesqdmczdfgple1@ccmail.com"
  }

##################

POST http://localhost:3333/auth/signin
Content-Type: application/json

 {
    "username": "neru",
    "password": "Azertyzofn"
  }

###################


PUT http://localhost:3333/api/auth/update/1
Content-Type: application/json

{
    "username": "Neruso",
    "email": "nelson.ntepp@icloud.com",
    "password": "yyr5wzfph3emV*"
}

####################

DELETE http://localhost:3333/users/12